print("Les types en Python :")
print("Les chaines de caractères")
print("les nombres")
print("les booléens")
print("les types séquentielles : listes, tuples")
print("les types d'ensembles : set, frozenset")
print("les types de correspondances : dictionnaires")
